"use client";

import { CalendarPlus, ClipboardCheck, Plus, Wrench, X } from "lucide-react";
import { useActionState, useState } from "react";

import {
  createMaintenanceTicketAction,
  createScheduleAction,
  recordAttendanceAction,
} from "@/features/operations/application/operations-actions";
import type { OperationActionState } from "@/features/operations/application/operations-actions";
import type { EnrollmentOption, ScheduleOption } from "@/features/operations/infrastructure/campus-operations.repository";
import { cn } from "@/lib/utils";

const fieldClass = "mt-2 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-blue-400 focus:ring-4 focus:ring-blue-50";
const initialOperationState: OperationActionState = { message: "", status: "idle" };

function ActionDialog({ children, description, onClose, title }: { children: React.ReactNode; description: string; onClose: () => void; title: string }) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4 backdrop-blur-sm"><button aria-label="Close dialog" className="absolute inset-0" onClick={onClose} type="button" /><div aria-modal="true" className="relative z-10 max-h-[calc(100vh-2rem)] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl sm:p-8" role="dialog"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Operational workflow</p><h2 className="mt-1 text-2xl font-semibold text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></div><button aria-label="Close dialog" className="rounded-xl p-2 text-slate-400 hover:bg-slate-100" onClick={onClose} type="button"><X className="size-5" /></button></div>{children}</div></div>;
}

function ActionMessage({ message, status }: { message: string; status: "idle" | "error" | "success" }) {
  return message ? <p aria-live="polite" className={cn("rounded-xl px-4 py-3 text-sm", status === "success" ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700")}>{message}</p> : null;
}

export function AttendanceRecorder({ canManage, enrollments }: { canManage: boolean; enrollments: EnrollmentOption[] }) {
  const [open, setOpen] = useState(false);
  const [state, action, pending] = useActionState(recordAttendanceAction, initialOperationState);
  if (!canManage) return null;
  return <><button className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-200 hover:bg-blue-700" onClick={() => setOpen(true)} type="button"><ClipboardCheck className="size-4" /> Record attendance</button>{open ? <ActionDialog description="Upsert a daily record. Existing attendance for the same enrollment and date will be corrected safely." onClose={() => setOpen(false)} title="Record attendance"><form action={action} className="mt-7 grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-sm font-medium text-slate-700">Student and course</span><select className={fieldClass} name="enrollmentId" required><option value="">Select enrollment</option>{enrollments.map((item) => <option key={item.id} value={item.id}>{item.student} · {item.course}</option>)}</select></label><label><span className="text-sm font-medium text-slate-700">Session date</span><input className={fieldClass} defaultValue={new Date().toISOString().slice(0, 10)} name="sessionDate" required type="date" /></label><label><span className="text-sm font-medium text-slate-700">Status</span><select className={fieldClass} name="status" required><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="excused">Excused</option></select></label><div className="sm:col-span-2"><ActionMessage {...state} /></div><div className="flex justify-end gap-3 sm:col-span-2"><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold" onClick={() => setOpen(false)} type="button">Done</button><button className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50" disabled={pending || !enrollments.length} type="submit">{pending ? "Saving…" : "Save attendance"}</button></div></form></ActionDialog> : null}</>;
}

export function ScheduleCreator({ canManage, offerings, rooms }: { canManage: boolean; offerings: ScheduleOption[]; rooms: ScheduleOption[] }) {
  const [open, setOpen] = useState(false);
  const [state, action, pending] = useActionState(createScheduleAction, initialOperationState);
  if (!canManage) return null;
  return <><button className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-200 hover:bg-blue-700" onClick={() => setOpen(true)} type="button"><CalendarPlus className="size-4" /> Schedule session</button>{open ? <ActionDialog description="Capacity and room-overlap constraints are checked before a session is committed." onClose={() => setOpen(false)} title="Schedule a session"><form action={action} className="mt-7 grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-sm font-medium text-slate-700">Course offering</span><select className={fieldClass} name="offeringId" required><option value="">Select offering</option>{offerings.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="sm:col-span-2"><span className="text-sm font-medium text-slate-700">Room</span><select className={fieldClass} name="roomId" required><option value="">Select room</option>{rooms.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label><span className="text-sm font-medium text-slate-700">Starts</span><input className={fieldClass} name="startsAt" required type="datetime-local" /></label><label><span className="text-sm font-medium text-slate-700">Ends</span><input className={fieldClass} name="endsAt" required type="datetime-local" /></label><div className="sm:col-span-2"><ActionMessage {...state} /></div><div className="flex justify-end gap-3 sm:col-span-2"><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold" onClick={() => setOpen(false)} type="button">Done</button><button className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50" disabled={pending || !offerings.length || !rooms.length} type="submit">{pending ? "Checking…" : "Create session"}</button></div></form></ActionDialog> : null}</>;
}

export function MaintenanceTicketCreator({ canManage, equipment, rooms }: { canManage: boolean; equipment: Array<{ id: string; label: string; roomId: string }>; rooms: ScheduleOption[] }) {
  const [open, setOpen] = useState(false);
  const [roomId, setRoomId] = useState("");
  const [state, action, pending] = useActionState(createMaintenanceTicketAction, initialOperationState);
  if (!canManage) return null;
  const roomEquipment = equipment.filter((item) => item.roomId === roomId);
  return <><button className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-200 hover:bg-blue-700" onClick={() => setOpen(true)} type="button"><Plus className="size-4" /> Open ticket</button>{open ? <ActionDialog description="Create a prioritized work item. Facility readiness and SLA monitoring update immediately." onClose={() => setOpen(false)} title="Open maintenance ticket"><form action={action} className="mt-7 grid gap-5 sm:grid-cols-2"><label><span className="text-sm font-medium text-slate-700">Room</span><select className={fieldClass} name="roomId" onChange={(event) => setRoomId(event.target.value)} required value={roomId}><option value="">Select room</option>{rooms.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label><span className="text-sm font-medium text-slate-700">Equipment (optional)</span><select className={fieldClass} disabled={!roomId} name="equipmentId"><option value="">Room-level issue</option>{roomEquipment.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="sm:col-span-2"><span className="text-sm font-medium text-slate-700">Title</span><input className={fieldClass} maxLength={160} name="title" placeholder="Projector is not powering on" required /></label><label className="sm:col-span-2"><span className="text-sm font-medium text-slate-700">Description</span><textarea className={fieldClass} name="description" placeholder="Describe the observed fault and operational impact." required rows={4} /></label><label><span className="text-sm font-medium text-slate-700">Priority</span><select className={fieldClass} name="priority" required><option value="medium">Medium</option><option value="low">Low</option><option value="high">High</option><option value="critical">Critical</option></select></label><div className="sm:col-span-2"><ActionMessage {...state} /></div><div className="flex justify-end gap-3 sm:col-span-2"><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold" onClick={() => setOpen(false)} type="button">Done</button><button className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50" disabled={pending || !rooms.length} type="submit"><Wrench className="mr-2 inline size-4" />{pending ? "Opening…" : "Open ticket"}</button></div></form></ActionDialog> : null}</>;
}
