import { ArrowRight, BookOpen, CalendarDays, CheckSquare2, Clock3, GraduationCap, Sparkles, UserCheck, UsersRound } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";

import { StatusPill } from "@/components/operations/operations-ui";
import { Card } from "@/design-system/primitives/card";
import { loadFacultyRoleWorkspace } from "@/features/workspaces/infrastructure/role-workspace.repository";
import { getCampusAccess } from "@/server/auth/campus-access";

export const dynamic = "force-dynamic";

const time = (value: string) => new Intl.DateTimeFormat("en-IN", { hour: "numeric", minute: "2-digit" }).format(new Date(value));

export default async function FacultyWorkspacePage() {
  const access = await getCampusAccess();
  if (!access) redirect("/faculty/sign-in");
  if (access.role !== "faculty") redirect("/access-denied?reason=role-mismatch&portal=faculty");
  const data = await loadFacultyRoleWorkspace(access.userId);

  if (!data.linked) return <section className="mx-auto max-w-4xl py-8 sm:py-14"><div className="rounded-[28px] border border-violet-100 bg-gradient-to-br from-violet-50 via-white to-blue-50 p-7 sm:p-10"><span className="grid size-12 place-items-center rounded-2xl bg-violet-600 text-white"><UsersRound className="size-5" /></span><p className="mt-7 text-sm font-semibold text-violet-700">Faculty workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-4xl">Let&apos;s connect your teaching profile, {data.name}.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-600">Your sign-in is working. A college administrator only needs to link this account to your employee number; your classes, attendance tasks, and learners will then be organized here.</p><div className="mt-7 flex gap-3"><Link className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white" href="/profile">Check my profile</Link><Link className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700" href="/notifications">View messages</Link></div></div></section>;

  return <section className="space-y-6">
    <div className="overflow-hidden rounded-[28px] bg-gradient-to-br from-violet-700 to-blue-700 p-6 text-white sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-violet-200">Teaching workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Good morning, {data.name}.</h1><p className="mt-3 text-sm text-blue-100">{data.designation} · {data.employeeNumber} · {data.department}</p></div><div className="flex flex-wrap gap-3"><Link className="inline-flex items-center gap-2 rounded-xl border border-white/25 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white" href="/student-approvals"><UserCheck className="size-4" />Student approvals</Link><Link className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-950" href="/attendance">Take attendance <ArrowRight className="size-4" /></Link></div></div></div>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ icon: CalendarDays, label: "Classes today", value: data.todayClasses.length, detail: "Your teaching schedule" }, { icon: BookOpen, label: "My courses", value: data.courses.length, detail: "Assigned sections" }, { icon: GraduationCap, label: "My students", value: data.studentCount, detail: "Across your courses" }, { icon: CheckSquare2, label: "Attendance pending", value: data.attendancePending, detail: "Student records today" }].map(({ detail, icon: Icon, label, value }) => <Card className="p-5" key={label}><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><Icon className="size-4.5" /></span><p className="mt-4 text-sm font-medium text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></Card>)}</div>

    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5 sm:px-6"><div><h2 className="font-semibold text-slate-950">Today&apos;s teaching</h2><p className="mt-1 text-sm text-slate-500">Classes, rooms, and attendance in one view.</p></div><CalendarDays className="size-5 text-violet-600" /></div><div className="divide-y divide-slate-100">{data.todayClasses.length ? data.todayClasses.map((session) => <div className="flex items-center gap-4 p-5 sm:px-6" key={session.id}><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-700"><Clock3 className="size-5" /></span><div className="min-w-0 flex-1"><p className="font-semibold text-slate-900">{session.course}</p><p className="mt-1 text-sm text-slate-500">{time(session.startsAt)}–{time(session.endsAt)} · {session.room}</p></div><Link className="text-xs font-semibold text-violet-700" href="/attendance">Attendance</Link></div>) : <div className="p-8 text-center"><CalendarDays className="mx-auto size-7 text-slate-300" /><p className="mt-3 font-semibold text-slate-800">No teaching sessions today</p><p className="mt-1 text-sm text-slate-500">Your next scheduled class will appear here.</p></div>}</div></Card><Card className="border-violet-100 bg-violet-50/60 p-5 sm:p-6"><span className="grid size-11 place-items-center rounded-xl bg-white text-violet-700 shadow-sm"><Sparkles className="size-5" /></span><h2 className="mt-5 text-xl font-semibold tracking-tight text-slate-950">Ask Aventra for help</h2><p className="mt-2 text-sm leading-6 text-slate-600">Review attendance risk, classroom readiness, or course signals using verified college data. You remain in control of every action.</p><Link className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-violet-700" href="/agents">Open faculty assistant <ArrowRight className="size-4" /></Link></Card></div>

    <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5 sm:px-6"><div><h2 className="font-semibold text-slate-950">My courses</h2><p className="mt-1 text-sm text-slate-500">Quick access to every section you teach.</p></div><Link className="text-sm font-semibold text-blue-700" href="/courses">View catalog</Link></div><div className="grid md:grid-cols-2 xl:grid-cols-3">{data.courses.map((course, index) => <div className={`p-5 sm:p-6 ${index ? "border-t border-slate-100 md:border-l md:border-t-0" : ""}`} key={course.id}><div className="flex items-center justify-between"><span className="font-mono text-xs font-bold text-violet-700">{course.code} · {course.section}</span><StatusPill tone="good">{course.enrolled} students</StatusPill></div><p className="mt-4 font-semibold text-slate-950">{course.title}</p><div className="mt-5 flex gap-4"><Link className="text-xs font-semibold text-blue-700" href="/attendance">Attendance</Link><Link className="text-xs font-semibold text-slate-600" href="/students">Learners</Link></div></div>)}</div></Card>
  </section>;
}
